Home/urls.py
from django.urls import path

from . import views

urlpatterns = [
<<<<<<< f4fc776c58b415edc252e933b892089ccaaede05:Home/urls.py
    path('', views.index, name='index'),
]
=======
    path('editor/', views.editor, name='editor'), #编辑器测试
    path('index/', views.index, name='index')
]
>>>>>>> Introfuce:Introduce/urls.py

Introduce/urls.py
from unicodedata import name
from urllib.parse import urlparse
from django.urls import path
from . import views

app_name = 'Introduce'

urlpatterns = [
    path('index/', views.index, name='index'),
    path('editor/', views.editor, name='editor'), #编辑器测试
    path('editor/<str:content>',views.editor_content),
    path('entity/', views.entity, name='entity'), #实体
    path('entity/<str:content>',views.entity_content),
    path('mate/', views.mate, name='mate'),#mate标签
    path('mate/<str:content>',views.mate_content),
    path('semantic/', views.semantic, name='semantic'),#语义化标签
    path('semantic/<str:content>',views.semantic_content),
    path('list/', views.list, name='list'),#列表
    path('list/<str:content>',views.list_content),
    # path('links/', views.links, name='links'),#超链接
    # path('links/<str:content>',views.links_content),
    # path('picture/',views.pciture, name='picture'),#图片标签
    # path('picture/<str:content>',views.picture_content),
    # path('inline/', views.inline, name='inline'),#内联标签
    # path('inline/<str:content>',views.inline_content),
    # path('multi/', views.multi, name='multi'),#媒体  
    # path('multi/<str:content>',views.multi_content),  
]

web_design/urls.py
from django.contrib import admin
from django.urls import include, path
from Home.views import index


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='home'),
    path('Introduce/', include('Introduce.urls')),  
]

Introduce/models.py
from django.db import models

# Create your models here.

Home/views.py
from django.shortcuts import render

from django.http import HttpResponse


def index(request):
    return render(request, 'index.html')

Introduce/views.py
from urllib import request
from django.shortcuts import render
from django.http import HttpResponse


# Create your views here.
def index(request):
    return render(request, 'introduce/index.html')

def editor(request):
    return render(request, 'introduce/editor/editor.html')

def editor_content(request,content):
    if content == 'examples':
        return render(request,'introduce/editor/examples.html')
    elif content == 'practice':
        return render(request,'introduce/editor/practice.html')
    else:
        return HttpResponse('---非法请求---')
        
def entity(request):
    return render(request, 'introduce/entity/entity.html')

def entity_content(request,content):
    if content == 'examples':
        return render(request,'introduce/entity/examples.html')
    elif content == 'practice':
        return render(request,'introduce/entity/practice.html')
    else:
        return HttpResponse('---非法请求---')


def mate(request):
    return render(request, 'introduce/mate/mate.html')

def mate_content(request,content):
    if content == 'examples':
        return render(request,'introduce/mate/examples.html')
    elif content == 'practice':
        return render(request,'introduce/mate/practice.html')
    else:
        return HttpResponse('---非法请求---')

def semantic(request):
    return render(request, 'introduce/semantic/semantic.html')

def semantic_content(request,content):
    if content == 'examples':
        return render(request,'introduce/semantic/examples.html')
    elif content == 'practice':
        return render(request,'introduce/semantic/practice.html')
    else:
        return HttpResponse('---非法请求---')

def list(request):
    return render(request, "introduce/list/list.html")

def list_content(request,content):
    if content == 'examples':
        return render(request,'introduce/list/examples.html')
    elif content == 'practice':
        return render(request,'introduce/list/practice.html')
    else:
        return HttpResponse('---非法请求---')

def links(request):
    return render(request, "links.html")

def pciture(request):
    return render(request, "picture.html")

def inline(request):
    return render(request, "inline.html")

def multi(request):
    return render(request, "multi.html")

def editor_Examples(request):
    return render(request,'editor_Examples.html')

Home/templates/base.html
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
<!DOCTYPE html>
<!-- 网站主语言 -->
<html lang="zh-cn">

<head>
    <!-- 网站采用的字符编码 -->
    <meta charset="utf-8">
    <!-- 预留网站标题的位置 -->
    <title>{% block title %}{% endblock %}</title>
    <!-- 引入bootstrap的css文件 -->
</head>

<body>
    <!-- 引入导航栏 -->
    {% include 'header.html' %}
    <!-- 预留具体页面的位置 -->
    <div class="row">
        <div class="col-1">{% block leftcontent %}{% endblock leftcontent %}</div>
        <div class="col-10">{% block content %}{% endblock content %}</div>
        <div class="col-1">{% block rightcontent %}{% endblock rightcontent %}</div>
      </div>
    <!-- 引入注脚 -->
    {% include 'footer.html' %}
</body>

</html>

Home/templates/footer.html
<div>
    <br><br><br>
</div>
<footer class="py-3 bg-dark fixed-bottom">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; www.dusaiphoto.com 2018</p>
    </div>
</footer>

Home/templates/header.html
<nav class="navbar navbar-dark bg-dark">
  <nav class="navbar navbar-expand-lg navbar-light">
    <a class="navbar-brand">YOLO</a>
      <ul class="navbar-nav">
        <li class="nav-item ">
          <a class="nav-link" href="{% url 'home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'Introduce:index' %}">Introduce</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">CSS</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Layout</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Float</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Position</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Font&background</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">HTML</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Animation</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Less</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Flex</a>
        </li>
      </ul>
      
  </nav>
</nav>

Home/templates/index.html
{% extends "base.html" %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
    首页
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}

{% endblock content %}

Introduce/templates/introduce/base.html
{% load bootstrap4 %}
{% bootstrap_css %}
{% load static %}
{% bootstrap_javascript jquery='full' %}
<!DOCTYPE html>
<!-- 网站主语言 -->
<html lang="zh-cn">

<head>
    <!-- 网站采用的字符编码 -->
    <meta charset="utf-8">
    <!-- 预留网站标题的位置 -->
    <title>{% block title %}{% endblock %}</title>
    <!-- 引入bootstrap的css文件 -->
    <link rel="stylesheet" href="{% static 'CSS/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'CSS/main.css' %}">
</head>

<body>
  {% include 'header.html' %}
  <br/>
        <div class="row">
            <div class="col-1">{% block leftcontent %}{% endblock leftcontent %}</div>
            <div class="col-10">{% block content %}{% endblock content %}</div>
            <div class="col-1">{% block rightcontent %}{% endblock rightcontent %}</div>
          </div>
      </div>
      <div class="col align-self-end">
        {% include 'footer.html' %}
      </div>
</body>

</html>

Introduce/templates/introduce/index.html
{% extends "introduce/base.html" %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
    Introduce
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block leftcontent %}
<nav class="nav flex-column">
    <a class="nav-link" href="/Introduce/editor/">编辑器测试</a>
    <a class="nav-link" href="/Introduce/entity/">实体</a>
    <a class="nav-link" href="/Introduce/mate/">mate标签</a>
    <a class="nav-link" href="/Introduce/semantic/">语义化标签</a>
    <a class="nav-link" href="/Introduce/list/">列表</a>
    <a class="nav-link" href="/Introduce/links/">超链接</a>
    <a class="nav-link" href="/Introduce/picture/">图片标签</a>
    <a class="nav-link" href="/Introduce/inline/">内联框架</a>
    <a class="nav-link" href="/Introduce/multi/">音视频</a>
</nav>
{% endblock leftcontent %}
{% block content %}
{% endblock content %}

Introduce/templates/introduce/inline/examples.html
{% extends "I_base.html" %}
{% load static %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% block title %}Editor{% endblock %}
{% block content %}
<body>
  <div class="card">
      <div class="card-header">
        <ul class="nav nav-tabs card-header-tabs">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'Introduce:editor' %}">理论讲解</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'Introduce:editor_Examples' %}">效果展示</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">代码练习</a>
          </li>
        </ul>
      </div>
    </div>


</body>  
{% endblock content %}

Introduce/templates/introduce/inline/inline.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Inline</title>
        <link rel="stylesheet" href="{% static 'CSS/normalize.css' %}">
        <link rel="stylesheet" href="{% static 'CSS/main.css' %}">
    </head>
    <body>
        <h3>8.内联框架</h3>
        <ul>
            <li>
                <p>内联框架，用于向当前页面引入一个其他页面</p>
                <ul>
                    <li>
                        <mark>src</mark>
                        指定要引入的网页的路径</li>
                    <li>
                        <mark>frameborder</mark>
                        指定内联框架的边框</li>

                </ul>
            </li>

        </ul>
        <pre>
            
            &lt;!doctype html&gt;
            &lt;html lang=&quot;en&quot;&gt;
            &lt;head&gt;
                &lt;meta charset=&quot;utf-8&quot;&gt;
                &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
                &lt;meta http-equiv=&quot;x-ua-compatible&quot; content=&quot;ie=edge&quot;&gt;
                &lt;title&gt;document&lt;/title&gt;
            &lt;/head&gt;
            &lt;body&gt;
                &lt;iframe src=&quot;https://www.qq.com&quot; width=&quot;800&quot; height=&quot;600&quot; frameborder=&quot;0&quot;&gt;&lt;/iframe&gt;
                &lt;h1&gt;hello&lt;/h1&gt;

                
            &lt;/body&gt;
            &lt;/html&gt;
        </pre>
    </body>
</html>

Introduce/templates/introduce/inline/practice.html
{% extends "I_base.html" %}
{% load static %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% block title %}Editor{% endblock %}
{% block content %}
<body>
  <div class="card">
      <div class="card-header">
        <ul class="nav nav-tabs card-header-tabs">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'Introduce:editor' %}">理论讲解</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'Introduce:editor_Examples' %}">效果展示</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">代码练习</a>
          </li>
        </ul>
      </div>
    </div>


</body>  
{% endblock content %}

Introduce/templates/introduce/links/examples.html
{% extends "I_base.html" %}
{% load static %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% block title %}Editor{% endblock %}
{% block content %}
<body>
  <div class="card">
      <div class="card-header">
        <ul class="nav nav-tabs card-header-tabs">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'Introduce:editor' %}">理论讲解</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'Introduce:editor_Examples' %}">效果展示</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">代码练习</a>
          </li>
        </ul>
      </div>
    </div>


</body>  
{% endblock content %}

Introduce/templates/introduce/links/practice.html
{% extends "I_base.html" %}
{% load static %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% block title %}Editor{% endblock %}
{% block content %}
<body>
  <div class="card">
      <div class="card-header">
        <ul class="nav nav-tabs card-header-tabs">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'Introduce:editor' %}">理论讲解</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'Introduce:editor_Examples' %}">效果展示</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">代码练习</a>
          </li>
        </ul>
      </div>
    </div>


</body>  
{% endblock content %}

Introduce/templates/introduce/list/examples.html
{% extends "introduce/base.html" %}
{% load static %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% block title %}Examples{% endblock %}
{% block content %}
    <body>
        <div class="card">
            <div class="card-header">
                <ul class="nav nav-tabs card-header-tabs">
                    <li class="nav-item">
                        <a class="nav-link" href="/Introduce/list">理论讲解</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="/Introduce/list/examples">效果展示</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Introduce/list/practice">代码练习</a>
                    </li>
                </ul>
            </div>
            <div class="web-body">
              <ul>
                <li>结构</li>
                <li>表现</li>
                <li>行为</li>
            </ul>

            <ol>
                <li>结构</li>
                <li>表现</li>
                <li>行为</li>
            </ol>


            <dl>
                <dt>结构</dt>
                <dd>结构表示网页的结构，结构用来规定网页中哪里是标题，哪里是段落</dd>
                <dd>结构表示网页的结构，结构用来规定网页中哪里是标题，哪里是段落</dd>
                <dd>结构表示网页的结构，结构用来规定网页中哪里是标题，哪里是段落</dd>
            </dl>

            <ul>
                <li>
                    aa
                    <ul>
                        <li>aa-1</li>
                        <li>aa-2
                            <ul>
                                <li>aa-1</li>
                                <li>aa-2</li>
                            </ul>
                        </li>
                    </ul>
                </li>
            </ul>
            </div>
        </div>
    </body>
{% endblock content %}

Introduce/templates/introduce/list/practice.html
{% extends "introduce/base.html" %}
{% load static %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% block title %}Practice{% endblock %}
{% block content %}
<body>
  <div class="card">
      <div class="card-header">
        <ul class="nav nav-tabs card-header-tabs">
          <li class="nav-item">
            <a class="nav-link" href="/Introduce/entity">理论讲解</a>
          </li>
          <li class="nav-item">
            <a class="nav-link " href="/Introduce/entity/examples">效果展示</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="/Introduce/entity/practice">代码练习</a>
          </li>
        </ul>
      </div>
      <div class="web-body">
        <h3>暂无练习</h3>
      </div>
    </div>
</body>  
{% endblock content %}

Introduce/templates/introduce/mate/examples.html
{% extends "introduce/base.html" %}
{% load static %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% block title %}Editor{% endblock %}
{% block content %}
    <body>
        <div class="card">
            <div class="card-header">
                <ul class="nav nav-tabs card-header-tabs">
                    <li class="nav-item">
                        <a class="nav-link" href="/Introduce/mate">理论讲解</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="/Introduce/mate/examples">效果展示</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Introduce/mate/practice">代码练习</a>
                    </li>
                </ul>
            </div>
        </div>
    </body>
{% endblock content %}

Introduce/templates/introduce/multi/examples.html
{% extends "I_base.html" %}
{% load static %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% block title %}Editor{% endblock %}
{% block content %}
<body>
  <div class="card">
      <div class="card-header">
        <ul class="nav nav-tabs card-header-tabs">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'Introduce:editor' %}">理论讲解</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'Introduce:editor_Examples' %}">效果展示</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">代码练习</a>
          </li>
        </ul>
      </div>
    </div>


</body>  
{% endblock content %}

Introduce/templates/introduce/multi/practice.html
{% extends "I_base.html" %}
{% load static %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% block title %}Editor{% endblock %}
{% block content %}
<body>
  <div class="card">
      <div class="card-header">
        <ul class="nav nav-tabs card-header-tabs">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'Introduce:editor' %}">理论讲解</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'Introduce:editor_Examples' %}">效果展示</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">代码练习</a>
          </li>
        </ul>
      </div>
    </div>


</body>  
{% endblock content %}

Introduce/templates/introduce/picture/examples.html
{% extends "I_base.html" %}
{% load static %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% block title %}Editor{% endblock %}
{% block content %}
<body>
  <div class="card">
      <div class="card-header">
        <ul class="nav nav-tabs card-header-tabs">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'Introduce:editor' %}">理论讲解</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'Introduce:editor_Examples' %}">效果展示</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">代码练习</a>
          </li>
        </ul>
      </div>
    </div>


</body>  
{% endblock content %}

Introduce/templates/introduce/picture/practice.html
{% extends "I_base.html" %}
{% load static %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% block title %}Editor{% endblock %}
{% block content %}
<body>
  <div class="card">
      <div class="card-header">
        <ul class="nav nav-tabs card-header-tabs">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'Introduce:editor' %}">理论讲解</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'Introduce:editor_Examples' %}">效果展示</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">代码练习</a>
          </li>
        </ul>
      </div>
    </div>


</body>  
{% endblock content %}